parent: classic
name: metzgerei_walz_template
display_name: Child theme of classic's theme
version: 1.0.0
assets:
  use_parent_assets: false

global_settings:
  hooks:
    displayTopColumn:
      - angebotsmodul
      - kalendermodul